/// Dish-specific ingredients for African countries (TheMealDB photo slugs).
const Map<String, List<String>> kAfricaIngredients = {
  'AO': ['Salmon', 'Spinach', 'Coconut', 'Onion', 'Garlic', 'Thyme', 'Lime'],
  'BJ': ['Salmon', 'Ginger', 'Lime', 'Garlic', 'Onion', 'Chili', 'Olive oil'],
  'BW': ['Beef', 'Mushrooms', 'Onion', 'Flour', 'Butter', 'Potato', 'Parsley'],
  'BF': ['Potato', 'Egg', 'Tomato', 'Onion', 'Chili', 'Olive oil', 'Carrot'],
  'BI': ['Lamb', 'Onion', 'Tomato', 'Garlic', 'Ginger', 'Rice', 'Chili'],
  'CV': ['Pork', 'Garlic', 'Paprika', 'Olive oil', 'Lemon', 'Salt', 'Pepper'],
  'CM': ['Tomato', 'Egg', 'Onion', 'Garlic', 'Cumin', 'Olive oil', 'Pepper'],
  'CF': ['Rice', 'Lentils', 'Tomato', 'Onion', 'Chickpeas', 'Garlic', 'Pasta'],
  'TD': ['Flour', 'Yeast', 'Sesame', 'Salt', 'Water', 'Oil', 'Sugar'],
  'KM': ['Rice noodles', 'Coconut', 'Salmon', 'Chili', 'Lime', 'Garlic', 'Ginger'],
  'CD': ['Potato', 'Salmon', 'Onion', 'Tomato', 'Chili', 'Garlic', 'Oil'],
  'CG': ['Spinach', 'Coconut', 'Garlic', 'Onion', 'Thyme', 'Salmon', 'Chili'],
  'DJ': ['Kidney Beans', 'Coconut', 'Garlic', 'Onion', 'Thyme', 'Ham', 'Chili'],
  'EG': ['Chickpeas', 'Olive oil', 'Garlic', 'Lemon', 'Cumin', 'Onion', 'Parsley'],
  'GQ': ['Bread', 'Pork', 'Garlic', 'Paprika', 'Olive oil', 'Egg', 'Wine'],
  'ER': ['Eggplant', 'Sesame', 'Garlic', 'Lemon', 'Olive oil', 'Salt', 'Parsley'],
  'SZ': ['Beef', 'Egg', 'Breadcrumbs', 'Flour', 'Lemon', 'Garlic', 'Oil'],
  'ET': ['Beef', 'Onion', 'Butter', 'Garlic', 'Ginger', 'Rice', 'Cumin'],
  'GA': ['Prawns', 'Chili', 'Garlic', 'Lime', 'Butter', 'Rice', 'Parsley'],
  'GM': ['Cashews', 'Flour', 'Sugar', 'Butter', 'Egg', 'Honey', 'Lemon'],
  'GH': ['Rice', 'Tomato', 'Onion', 'Chicken', 'Thyme', 'Garlic', 'Chili'],
  'GN': ['Rice', 'Chicken', 'Egg', 'Soy sauce', 'Onion', 'Carrot', 'Peas'],
  'GW': ['Salmon', 'Lemon', 'Garlic', 'Onion', 'Rice', 'Chili', 'Parsley'],
  'CI': ['Lentils', 'Sesame', 'Lemon', 'Garlic', 'Onion', 'Tomato', 'Cumin'],
  'KE': ['Beef', 'Coconut', 'Onion', 'Tomato', 'Garlic', 'Rice', 'Cumin'],
  'LS': ['Apple', 'Flour', 'Butter', 'Sugar', 'Cinnamon', 'Oats', 'Lemon'],
  'LR': ['Potato', 'Cabbage', 'Ham', 'Butter', 'Onion', 'Milk', 'Salt'],
  'LY': ['Carrot', 'Cumin', 'Onion', 'Garlic', 'Olive oil', 'Lemon', 'Coriander'],
  'MG': ['Chicken', 'Lemon', 'Onion', 'Ginger', 'Potato', 'Garlic', 'Rice'],
  'MW': ['Potato', 'Beef', 'Cheese', 'Tomato', 'Onion', 'Garlic', 'Lettuce'],
  'ML': ['Peanuts', 'Lamb', 'Tomato', 'Onion', 'Sweet Potato', 'Chili', 'Rice'],
  'MR': ['Lamb', 'Potato', 'Carrot', 'Onion', 'Chickpeas', 'Paprika', 'Garlic'],
  'MU': ['Oats', 'Flour', 'Coconut', 'Butter', 'Sugar', 'Honey', 'Baking soda'],
  'MA': ['Lamb', 'Apricot', 'Onion', 'Cinnamon', 'Ginger', 'Almonds', 'Honey'],
  'MZ': ['Chicken', 'Chili', 'Garlic', 'Lemon', 'Paprika', 'Olive oil', 'Onion'],
  'NA': ['Chicken', 'Honey', 'Garlic', 'Butter', 'Lemon', 'Rosemary', 'Vinegar'],
  'NE': ['Lamb', 'Potato', 'Carrot', 'Onion', 'Cabbage', 'Parsley', 'Tomato'],
  'NG': ['Rice', 'Tomato', 'Onion', 'Chicken', 'Thyme', 'Garlic', 'Chili'],
  'RW': ['Chicken', 'Rice', 'Egg', 'Breadcrumbs', 'Onion', 'Potato', 'Cumin'],
  'ST': ['Salmon', 'Tomato', 'Onion', 'Garlic', 'Thyme', 'Pepper', 'Lime'],
  'SN': ['Salmon', 'Rice', 'Tomato', 'Onion', 'Carrot', 'Cabbage', 'Chili'],
  'SC': ['Rice', 'Coconut', 'Salmon', 'Egg', 'Cucumber', 'Chili', 'Peanuts'],
  'SL': ['Carrot', 'Cumin', 'Garlic', 'Olive oil', 'Lemon', 'Paprika', 'Parsley'],
  'SO': ['Salmon', 'Egg', 'Parsley', 'Onion', 'Potato', 'Flour', 'Cumin'],
  'ZA': ['Beef', 'Garlic', 'Vinegar', 'Olive oil', 'Parsley', 'Salt', 'Pepper'],
  'SS': ['Flour', 'Egg', 'Sugar', 'Orange', 'Butter', 'Honey', 'Yeast'],
  'SD': ['Chickpeas', 'Sesame', 'Garlic', 'Lemon', 'Olive oil', 'Cumin', 'Paprika'],
  'TZ': ['Corn', 'Kidney Beans', 'Beef', 'Potato', 'Onion', 'Paprika', 'Tomato'],
  'TG': ['Tomato', 'Eggplant', 'Onion', 'Garlic', 'Olive oil', 'Pepper', 'Zucchini'],
  'TN': ['Chicken', 'Chickpeas', 'Carrot', 'Onion', 'Cinnamon', 'Tomato', 'Garlic'],
  'UG': ['Potato', 'Onion', 'Tomato', 'Peanuts', 'Chili', 'Garlic', 'Beef'],
  'ZM': ['Rice', 'Salmon', 'Egg', 'Butter', 'Onion', 'Cumin', 'Parsley'],
  'ZW': ['Lime', 'Egg', 'Milk', 'Sugar', 'Butter', 'Flour', 'Cream'],
};
