/// Dish-specific ingredients for Americas countries (TheMealDB photo slugs).
const Map<String, List<String>> kAmericasIngredients = {
  'AG': ['Tamarind', 'Sugar', 'Flour', 'Coconut', 'Butter', 'Cinnamon', 'Nutmeg'],
  'AR': ['Beef', 'Tomato', 'Cheese', 'Ham', 'Egg', 'Garlic', 'Oregano'],
  'BS': ['Cream', 'Sugar', 'Egg', 'Flour', 'Butter', 'Vanilla', 'Honey'],
  'BB': ['Lamb', 'Bread', 'Yogurt', 'Garlic', 'Lemon', 'Tomato', 'Oregano'],
  'BZ': ['Beef', 'Cheese', 'Tomato', 'Onion', 'Garlic', 'Bread', 'Pasta'],
  'BO': ['Flour', 'Sugar', 'Butter', 'Egg', 'Lemon', 'Milk', 'Cinnamon'],
  'BR': ['Beef', 'Onion', 'Cumin', 'Paprika', 'Flour', 'Egg', 'Olives'],
  'CA': ['Chicken', 'Tomato', 'Cheese', 'Onion', 'Chili', 'Coriander', 'Tortillas'],
  'CL': ['Beef', 'Pumpkin', 'Corn', 'Potato', 'Onion', 'Paprika', 'Rice'],
  'CO': ['Corn', 'Beef', 'Beans', 'Potato', 'Cheese', 'Onion', 'Tomato'],
  'CR': ['Chocolate', 'Coconut', 'Sugar', 'Butter', 'Flour', 'Egg', 'Nuts'],
  'CU': ['Chickpeas', 'Olive oil', 'Cumin', 'Garlic', 'Lemon', 'Bread', 'Salt'],
  'DM': ['Flour', 'Sugar', 'Butter', 'Cinnamon', 'Yeast', 'Oil', 'Honey'],
  'DO': ['Flour', 'Egg', 'Milk', 'Sugar', 'Butter', 'Honey', 'Vanilla'],
  'EC': ['Chicken', 'Peanuts', 'Soy sauce', 'Ginger', 'Garlic', 'Chili', 'Rice'],
  'SV': ['Chickpeas', 'Onion', 'Lime', 'Cumin', 'Tomato', 'Tortillas', 'Pepper'],
  'GD': ['Potato', 'Butter', 'Cheese', 'Corn', 'Onion', 'Garlic', 'Yogurt'],
  'GT': ['Rice noodles', 'Soy sauce', 'Chicken', 'Garlic', 'Egg', 'Onion', 'Beans'],
  'GY': ['Rice noodles', 'Prawns', 'Peanuts', 'Lime', 'Egg', 'Garlic', 'Beans'],
  'HT': ['Chicken', 'Coconut', 'Rice', 'Garlic', 'Onion', 'Lime', 'Chili'],
  'HN': ['Chicken', 'Soy sauce', 'Ginger', 'Garlic', 'Sugar', 'Rice', 'Lime'],
  'JM': ['Chicken', 'Onion', 'Garlic', 'Thyme', 'Potato', 'Tomato', 'Chili'],
  'NI': ['Rice', 'Prawns', 'Saffron', 'Tomato', 'Peas', 'Onion', 'Garlic'],
  'PA': ['Apple', 'Butter', 'Sugar', 'Flour', 'Egg', 'Cream', 'Cinnamon'],
  'PY': ['Corn', 'Beef', 'Cheese', 'Onion', 'Tomato', 'Butter', 'Salt'],
  'PE': ['Salmon', 'Lime', 'Onion', 'Chili', 'Corn', 'Potato', 'Coriander'],
  'KN': ['Kidney Beans', 'Pork', 'Onion', 'Tomato', 'Potato', 'Thyme', 'Garlic'],
  'LC': ['Pork', 'Flour', 'Egg', 'Milk', 'Onion', 'Butter', 'Salt'],
  'VC': ['Bread', 'Kidney Beans', 'Tomato', 'Olive oil', 'Garlic', 'Carrot', 'Onion'],
  'SR': ['Beef', 'Potato', 'Corn', 'Onion', 'Garlic', 'Coriander', 'Lime'],
  'TT': ['Rice', 'Chicken', 'Ginger', 'Garlic', 'Onion', 'Soy sauce', 'Salt'],
  'US': ['Beef', 'Kidney Beans', 'Tomato', 'Onion', 'Garlic', 'Chili', 'Cumin'],
  'UY': ['Chicken', 'Coconut', 'Rice', 'Onion', 'Garlic', 'Lime', 'Coriander'],
  'VE': ['Beef', 'Onion', 'Tomato', 'Garlic', 'Cumin', 'Potato', 'Pepper'],
};
