/// Dish-specific ingredients for Asian countries (TheMealDB photo slugs).
const Map<String, List<String>> kAsiaIngredients = {
  'AF': ['Lamb', 'Rice', 'Onion', 'Carrot', 'Raisins', 'Cumin', 'Salt'],
  'BD': ['Chicken', 'Yogurt', 'Ginger', 'Garlic', 'Lemon', 'Tomato', 'Cumin'],
  'BT': ['Chicken', 'Cashews', 'Onion', 'Ginger', 'Garlic', 'Rice', 'Chili'],
  'BN': ['Rice', 'Coconut', 'Sugar', 'Egg', 'Flour', 'Butter', 'Salt'],
  'KH': ['Chicken', 'Coconut', 'Peanuts', 'Lime', 'Fish sauce', 'Garlic', 'Ginger'],
  'CN': ['Beef', 'Rice noodles', 'Soy sauce', 'Ginger', 'Garlic', 'Cabbage', 'Sesame'],
  'HK': ['Pork', 'Prawns', 'Rice', 'Soy sauce', 'Ginger', 'Sesame', 'Cabbage'],
  'IN': ['Lamb', 'Rice', 'Yogurt', 'Onion', 'Saffron', 'Cumin', 'Mint'],
  'ID': ['Rice', 'Egg', 'Garlic', 'Onion', 'Chili', 'Soy sauce', 'Prawns'],
  'IR': ['Lamb', 'Onion', 'Rice', 'Tomato', 'Turmeric', 'Cumin', 'Parsley'],
  'KZ': ['Lamb', 'Cumin', 'Onion', 'Bread', 'Tomato', 'Garlic', 'Pepper'],
  'KG': ['Kidney Beans', 'Lamb', 'Onion', 'Garlic', 'Tomato', 'Rice', 'Cumin'],
  'LA': ['Rice noodles', 'Egg', 'Soy sauce', 'Garlic', 'Chili', 'Bean sprouts', 'Lime'],
  'MY': ['Beef', 'Coconut', 'Lemongrass', 'Garlic', 'Chili', 'Ginger', 'Rice'],
  'MV': ['Salmon', 'Coconut', 'Chili', 'Lime', 'Onion', 'Turmeric', 'Rice'],
  'MN': ['Beef', 'Rice noodles', 'Onion', 'Ginger', 'Garlic', 'Fish sauce', 'Basil'],
  'MM': ['Salmon', 'Rice noodles', 'Turmeric', 'Garlic', 'Ginger', 'Onion', 'Lime'],
  'NP': ['Cheese', 'Peas', 'Tomato', 'Onion', 'Ginger', 'Garlic', 'Cumin'],
  'KP': ['Rice noodles', 'Pork', 'Soy sauce', 'Egg', 'Spring Onions', 'Garlic', 'Ginger'],
  'PK': ['Chicken', 'Yogurt', 'Tomato', 'Onion', 'Ginger', 'Garlic', 'Cumin'],
  'PH': ['Beef', 'Soy sauce', 'Garlic', 'Lemon', 'Onion', 'Bay leaf', 'Pepper'],
  'SG': ['Chicken', 'Coconut', 'Chili', 'Lemongrass', 'Turmeric', 'Lime', 'Garlic'],
  'KR': ['Beef', 'Soy sauce', 'Garlic', 'Sesame', 'Sugar', 'Spring Onions', 'Pear'],
  'LK': ['Salmon', 'Chili', 'Garlic', 'Ginger', 'Onion', 'Coconut', 'Lime'],
  'TW': ['Beef', 'Rice noodles', 'Soy sauce', 'Cabbage', 'Garlic', 'Ginger', 'Onion'],
  'TJ': ['Lamb', 'Yogurt', 'Garlic', 'Cucumber', 'Bread', 'Onion', 'Dill'],
  'TH': ['Beef', 'Coconut', 'Peanuts', 'Potato', 'Onion', 'Cinnamon', 'Fish sauce'],
  'TL': ['Egg', 'Bread', 'Onion', 'Garlic', 'Chili', 'Cumin', 'Beef'],
  'TM': ['Lamb', 'Potato', 'Onion', 'Butter', 'Flour', 'Egg', 'Salt'],
  'UZ': ['Pork', 'Mushrooms', 'Tofu', 'Soy sauce', 'Vinegar', 'Chili', 'Ginger'],
  'VN': ['Beef', 'Bread', 'Carrot', 'Cucumber', 'Coriander', 'Chili', 'Garlic'],
};
