/// Dish-specific ingredients for European countries (TheMealDB photo slugs).
const Map<String, List<String>> kEuropeIngredients = {
  'AL': ['Eggplant', 'Lamb', 'Potato', 'Tomato', 'Onion', 'Olive oil', 'Cinnamon'],
  'AD': ['Potato', 'Olive oil', 'Paprika', 'Garlic', 'Tomato', 'Salt'],
  'AM': ['Lamb', 'Pork', 'Onion', 'Tomato', 'Garlic', 'Parsley'],
  'AT': ['Beef', 'Mushrooms', 'Butter', 'Egg', 'Onion', 'Flour'],
  'AZ': ['Yogurt', 'Cucumber', 'Garlic', 'Dill', 'Olive oil', 'Salt'],
  'BY': ['Mushrooms', 'Onion', 'Butter', 'Beef', 'Potato', 'Dill'],
  'BE': ['Beef', 'Onion', 'Bacon', 'Beer', 'Flour', 'Butter'],
  'BA': ['Beef', 'Lamb', 'Onion', 'Garlic', 'Paprika', 'Bread'],
  'BG': ['Flour', 'Cheese', 'Eggs', 'Butter', 'Yogurt', 'Oil'],
  'HR': ['Beef', 'Onion', 'Paprika', 'Tomato', 'Potato', 'Garlic'],
  'CY': ['Tomato', 'Olive oil', 'Onion', 'Garlic', 'Dill', 'Lemon'],
  'CZ': ['Beef', 'Cream', 'Onion', 'Carrot', 'Cranberry', 'Flour'],
  'DK': ['Pork', 'Egg', 'Flour', 'Onion', 'Butter', 'Lemon'],
  'EE': ['Pork', 'Sauerkraut', 'Onion', 'Carrot', 'Barley', 'Bay leaf'],
  'FI': ['Mushrooms', 'Cream', 'Garlic', 'Butter', 'Parsley', 'Flour'],
  'FR': ['Chicken', 'Bacon', 'Mushrooms', 'Onion', 'Butter', 'Red wine'],
  'GE': ['Flour', 'Beef', 'Pork', 'Onion', 'Cilantro', 'Black pepper'],
  'DE': ['Cabbage', 'Pork', 'Flour', 'Potato', 'Onion', 'Butter'],
  'GR': ['Prawns', 'Tomato', 'Feta', 'Olive oil', 'Garlic', 'Lemon'],
  'HU': ['Beef', 'Paprika', 'Onion', 'Sour cream', 'Flour', 'Garlic'],
  'IS': ['Almonds', 'Egg', 'Sugar', 'Butter', 'Cream', 'Vanilla'],
  'IE': ['Beef', 'Potato', 'Carrot', 'Onion', 'Barley', 'Parsley'],
  'XK': ['Spaghetti', 'Tomato', 'Olive oil', 'Garlic', 'Basil', 'Cheese'],
  'LV': ['Chicken', 'Carrot', 'Onion', 'Parsley', 'Bay leaf', 'Pepper'],
  'LI': ['Cheese', 'Honey', 'Eggs', 'Flour', 'Butter', 'Cream'],
  'LT': ['Flour', 'Butter', 'Egg', 'Sugar', 'Jam', 'Milk'],
  'LU': ['Beef', 'Bacon', 'Mushrooms', 'Onion', 'Carrot', 'Red wine'],
  'MD': ['Potato', 'Mustard', 'Butter', 'Onion', 'Milk', 'Garlic'],
  'MC': ['Almonds', 'Garlic', 'Olive oil', 'Bread', 'Cream', 'Lemon'],
  'ME': ['Ham', 'Potato', 'Egg', 'Flour', 'Cheese', 'Breadcrumbs'],
  'NL': ['Potato', 'Carrot', 'Onion', 'Bacon', 'Butter', 'Milk'],
  'MK': ['Lamb', 'Tomato', 'Onion', 'Paprika', 'Garlic', 'Pepper'],
  'NO': ['Almonds', 'Sugar', 'Egg', 'Flour', 'Butter', 'Vanilla'],
  'PT': ['Salmon', 'Olive oil', 'Lemon', 'Garlic', 'Salt', 'Paprika'],
  'RO': ['Lamb', 'Tomato', 'Onion', 'Garlic', 'Yogurt', 'Paprika'],
  'RU': ['Beef', 'Mushrooms', 'Onion', 'Sour cream', 'Butter', 'Mustard'],
  'SM': ['Spaghetti', 'Beef', 'Tomato', 'Onion', 'Cheese', 'Milk'],
  'RS': ['Spaghetti', 'Pork', 'Tomato', 'Onion', 'Paprika', 'Garlic'],
  'SK': ['Flour', 'Cabbage', 'Mushrooms', 'Onion', 'Egg', 'Butter'],
  'SI': ['Walnuts', 'Flour', 'Honey', 'Egg', 'Butter', 'Milk'],
  'ES': ['Rice', 'Pork', 'Tomato', 'Potato', 'Chickpeas', 'Saffron'],
  'SE': ['Almonds', 'Butter', 'Flour', 'Egg', 'Sugar', 'Cardamom'],
  'CH': ['Salmon', 'Potato', 'Cream', 'Onion', 'Butter', 'White wine'],
  'TR': ['Lamb', 'Paprika', 'Garlic', 'Onion', 'Tomato', 'Yogurt'],
  'UA': ['Beetroot', 'Cabbage', 'Potato', 'Beef', 'Sour cream', 'Dill'],
  'GB': ['Cod', 'Potato', 'Flour', 'Egg', 'Lemon', 'Salt'],
};
