/// Ingredient photos (TheMealDB — same style as food atlases: product shots on white).
const _base = 'https://www.themealdb.com/images/ingredients';

/// Display label → TheMealDB ingredient file name (without size suffix).
const _aliases = <String, String>{
  'eggs': 'Egg',
  'egg': 'Egg',
  'twaróg cheese': 'Cheese',
  'twarog cheese': 'Cheese',
  'pecorino romano': 'Parmesan',
  'black pepper': 'Black Pepper',
  'guanciale': 'Bacon',
  'wheat noodles': 'Rice Noodles',
  'thin noodles': 'Spaghetti',
  'chashu': 'Pork',
  'fish stock': 'Fish Stock',
  'fish tacos': 'Fish',
  'cilantro': 'Coriander',
  'chili': 'Chilli',
  'chiles': 'Chilli',
  'chilli': 'Chilli',
  'scallion': 'Spring Onions',
  'spring onion': 'Spring Onions',
  'onion': 'Onion',
  'garlic': 'Garlic',
  'flour': 'Flour',
  'potatoes': 'Potato',
  'potato': 'Potato',
  'cabbage': 'Cabbage',
  'mushrooms': 'Mushrooms',
  'mushroom': 'Mushrooms',
  'butter': 'Butter',
  'sauerkraut': 'Sauerkraut',
  'spaghetti': 'Spaghetti',
  'pork': 'Pork',
  'lamb': 'Lamb',
  'beef': 'Beef',
  'cumin': 'Cumin',
  'paprika': 'Paprika',
  'parsley': 'Parsley',
  'shrimp': 'Prawns',
  'mussels': 'Mussels',
  'saffron': 'Saffron',
  'goat': 'Goat',
  'corn tortillas': 'Tortillas',
  'corn': 'Corn',
  'beans': 'Kidney Beans',
  'tomato': 'Tomato',
  'lime': 'Lime',
  'rice': 'Rice',
  'soy sauce': 'Soy Sauce',
  'sesame': 'Sesame Seed',
  'sesame seeds': 'Sesame Seed',
  'sesame seed': 'Sesame Seed',
  'ginger': 'Ginger',
  'herbs': 'Basil',
  'olive oil': 'Olive Oil',
  'salt': 'Salt',
  'oil': 'Olive Oil',
  'coconut': 'Coconut Milk',
  'root vegetables': 'Potato',
  'grains': 'Rice',
  'seafood': 'Salmon',
  'spices': 'Cumin',
  'noodles': 'Rice Noodles',
  'pork broth': 'Pork',
  'nori': 'Spinach',
  'seaweed': 'Spinach',
  'eggplant': 'Aubergine',
  'cinnamon': 'Cinnamon',
  'bell pepper': 'Red Pepper',
  'puff pastry': 'Puff Pastry',
  'yogurt': 'Yogurt',
  'cucumber': 'Cucumber',
  'dill': 'Dill',
  'buckwheat': 'Buckwheat',
  'beer': 'Beer',
  'bread': 'Bread',
  'butter beans': 'Kidney Beans',
  'cream': 'Cream',
  'carrot': 'Carrot',
  'cranberry': 'Cranberry',
  'capers': 'Capers',
  'barley': 'Oats',
  'kraut': 'Sauerkraut',
  'bay leaf': 'Bay Leaf',
  'chicken': 'Chicken',
  'red wine': 'Red Wine',
  'white wine': 'White Wine',
  'feta': 'Feta',
  'sour cream': 'Sour Cream',
  'almonds': 'Almonds',
  'vanilla': 'Vanilla',
  'basil': 'Basil',
  'cheese': 'Cheese',
  'jam': 'Strawberries',
  'mustard': 'Mustard',
  'breadcrumbs': 'Breadcrumbs',
  'bacon': 'Bacon',
  'ham': 'Ham',
  'beetroot': 'Beetroot',
  'chickpeas': 'Chickpeas',
  'walnuts': 'Walnuts',
  'cardamom': 'Cardamom',
  'leek': 'Leek',
  'cod': 'Cod',
  'haddock': 'Haddock',
  'white fish': 'Cod',
  'sardines': 'Salmon',
  'pepper': 'Black Pepper',
  'milk': 'Milk',
  'sugar': 'Sugar',
  'honey': 'Honey',
  'lemon': 'Lemon',
  'bread dumpling': 'Bread',
  'flatbread': 'Bread',
  'phyllo': 'Filo Pastry',
  'guinness': 'Beer',
  'smoked sausage': 'Sausages',
  'béchamel': 'Milk',
  'pearl onions': 'Onion',
  'coconut milk': 'Coconut Milk',
  'coconut cream': 'Coconut Cream',
  'fish sauce': 'Fish Sauce',
  'lemongrass': 'Lemongrass',
  'garam masala': 'Cumin',
  'paneer': 'Paneer',
  'peas': 'Peas',
  'miso': 'Soy Sauce',
  'vinegar': 'Vinegar',
  'baguette': 'Bread',
  'pear': 'Apple',
  'star anise': 'Star Anise',
  'curry powder': 'Curry Powder',
  'pate': 'Liver',
  'shallot': 'Onion',
  'apricot': 'Apricot',
  'raisins': 'Raisins',
  'turmeric': 'Turmeric',
  'galangal': 'Galangal',
  'peanuts': 'Peanuts',
  'red curry': 'Curry Powder',
  'mint': 'Mint',
  'bean sprouts': 'Bean Sprouts',
  'bok choy': 'Chinese Cabbage',
  'tofu': 'Tofu',
  'bamboo shoots': 'Mushrooms',
  'pickled carrot': 'Carrot',
  'pandan': 'Basil',
  'cashews': 'Cashews',
  'liver': 'Liver',
  'banana stem': 'Onion',
  'lentils': 'Lentils',
  'spinach': 'Spinach',
  'oats': 'Oats',
  'plantain': 'Banana',
  'sweet potato': 'Sweet Potato',
  'tortillas': 'Tortillas',
  'tamarind': 'Tamarind Paste',
  'nutmeg': 'Nutmeg',
  'oregano': 'Oregano',
  'olives': 'Olive',
  'pasta': 'Spaghetti',
  'chocolate': 'Chocolate',
  'nuts': 'Nuts',
  'pumpkin': 'Pumpkin',
  'zucchini': 'Zucchini',
  'lettuce': 'Lettuce',
  'rosemary': 'Rosemary',
  'baking soda': 'Baking Powder',
  'orange': 'Orange',
  'rosewater': 'Orange',
  'filo pastry': 'Filo Pastry',
  'ackee': 'Ackee',
  'saltfish': 'Salt Cod',
  'scotch bonnet': 'Scotch Bonnet',
  'harissa': 'Harissa',
  'wine': 'Red Wine',
  'yeast': 'Flour',
  'couscous': 'Couscous',
  'cornmeal': 'Corn',
  'condensed milk': 'Milk',
  'graham crackers': 'Digestive Biscuits',
  'graham cracker': 'Digestive Biscuits',
  'maple syrup': 'Honey',
  'mirin': 'Soy Sauce',
  'browning sauce': 'Soy Sauce',
  'doner': 'Doner Meat',
  'chimichurri herbs': 'Parsley',
  'teff': 'Rice',
  'berbere': 'Cumin',
  'fava beans': 'Kidney Beans',
  'tahini': 'Tahini',
  'golden syrup': 'Honey',
  'dulce de leche': 'Milk',
  'avocado': 'Avocado',
  'yuca': 'Potato',
  'cassava': 'Potato',
  'dates': 'Medjool Dates',
  'pistachios': 'Pistachio',
  'semolina': 'Flour',
  'pickles': 'Cucumber',
  'pomegranate': 'Pomegranate',
  'pineapple': 'Pineapple',
  'banana': 'Banana',
  'cloves': 'Cinnamon',
  'pastry': 'Filo Pastry',
  'jute leaves': 'Spinach',
};

/// Extra slugs tried when the primary TheMealDB image is missing (404).
const _fallbackSlugs = <String, List<String>>{
  'coconut': ['Coconut Cream'],
  'coconut milk': ['Coconut Cream'],
  'barley': ['Rice'],
  'sesame': ['Tahini'],
  'lemongrass': ['Ginger'],
};

List<String> ingredientImageSlugs(String displayName) {
  final key = displayName.trim().toLowerCase();
  final primary = _aliases[key] ?? _guessSlug(displayName);
  final extras = _fallbackSlugs[key];
  if (extras == null) return [primary];
  return [primary, ...extras.where((s) => s != primary)];
}

String ingredientImageUrl(String displayName) {
  final slug = ingredientImageSlugs(displayName).first;
  final encoded = Uri.encodeComponent(slug);
  return '$_base/$encoded-medium.png';
}

List<String> ingredientImageUrls(String displayName) {
  return ingredientImageSlugs(displayName)
      .map((slug) => '$_base/${Uri.encodeComponent(slug)}-medium.png')
      .toList();
}

String _guessSlug(String name) {
  final cleaned = name.trim();
  if (cleaned.isEmpty) return 'Salt';
  // Title-case each word for TheMealDB convention.
  return cleaned
      .split(RegExp(r'\s+'))
      .map((w) =>
          w.isEmpty ? w : '${w[0].toUpperCase()}${w.substring(1).toLowerCase()}')
      .join(' ');
}
