-- ─────────────────────────────────────────────────────────────────────────────
-- GastroVoyage — Extend the notifications type CHECK with `story_reaction`
-- Run this once in the Supabase SQL editor (or via psql) AFTER migration
-- 007_notifications.sql and 008_story_reactions.sql. Without this migration
-- the backend silently skips inserting story-reaction notifications (the
-- type would fail the CHECK constraint).
--
-- This migration is re-runnable: it drops the existing CHECK constraint by
-- name (the default Postgres autogenerated constraint name pattern) and
-- re-adds it. If the prior name doesn't exist (clean install / renamed),
-- the DROP is wrapped in a DO block that swallows the error.
--
-- After this migration:
--   • notifications.type now accepts `story_reaction` in addition to the
--     existing follow_request / follow_accepted / story_view / journey_week
--     / badge_earned set.
-- ─────────────────────────────────────────────────────────────────────────────

-- Drop any constraint on `notifications.type` (whatever its autogenerated
-- name) so the re-add below is idempotent. Postgres names CHECK constraints
-- `<table>_<column>_check` by default — we cover both that and a couple of
-- common manual variants for safety.
-- Drop the auto-named CHECK that migration 007 created inline (Postgres
-- default = `<table>_<column>_check`). Using IF EXISTS keeps it re-runnable.
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;

-- Belt-and-braces: drop any other CHECK constraint that still references the
-- `type` column. (The earlier dynamic filter `ILIKE '%type%IN%'` missed
-- because Postgres normalises `IN (...)` to `= ANY (ARRAY[...])`.)
DO $$
DECLARE
  con_name text;
BEGIN
  FOR con_name IN
    SELECT c.conname
      FROM pg_constraint c
      JOIN pg_attribute a
        ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
     WHERE c.conrelid = 'notifications'::regclass
       AND c.contype  = 'c'
       AND a.attname  = 'type'
  LOOP
    EXECUTE format('ALTER TABLE notifications DROP CONSTRAINT %I', con_name);
  END LOOP;
END$$;

-- Re-add the CHECK with the expanded allow-list. Naming it explicitly so a
-- subsequent migration can target it deterministically if needed.
ALTER TABLE notifications
  ADD CONSTRAINT notifications_type_check
  CHECK (type IN (
    'follow_request',
    'follow_accepted',
    'story_view',
    'story_reaction',
    'journey_week',
    'badge_earned'
  ));
